name = "fortfem"
version = "0.1.0"
license = "license"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
copyright = "Copyright 2025, Christopher Albert"
description = "A modern Fortran finite element library designed for ease of use, inspired by FreeFEM and FEniCS"
homepage = "https://github.com/itpplasma/fortfem"
keywords = ["finite-elements", "pde", "scientific-computing", "fortran", "fem"]
categories = ["science"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["lapack", "blas", "umfpack", "amd", "cholmod", "suitesparseconfig"]

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[extra.ford]
project = "FortFEM"
src_dir = "src"
output_dir = "build/doc"
page_dir = "doc"

[dependencies]
fortplotlib = { git = "https://github.com/krystophny/fortplotlib.git" }

[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive.git" }


