name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran liblapack-dev libsuitesparse-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install gfortran suite-sparse

    - name: Setup Fortran Package Manager
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          wget https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-linux-x86_64-gcc-12
          chmod +x fpm-0.12.0-linux-x86_64-gcc-12
          sudo mv fpm-0.12.0-linux-x86_64-gcc-12 /usr/local/bin/fpm
        elif [ "$RUNNER_OS" = "macOS" ]; then
          wget https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-macos-x86_64-gcc-12
          chmod +x fpm-0.12.0-macos-x86_64-gcc-12
          sudo mv fpm-0.12.0-macos-x86_64-gcc-12 /usr/local/bin/fpm
        fi

    - name: Build
      run: fpm build --profile release

    - name: Run tests
      run: fpm test

    - name: Run tests with coverage
      if: runner.os == 'Linux'
      run: |
        fpm test --flag "--coverage"
        gcov -o build/gfortran*/fortfem/test_* src/*.f90

    - name: Upload coverage to Codecov
      if: runner.os == 'Linux'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./*.gcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Build examples
      run: |
        fpm build --example

    - name: Run example
      run: |
        fpm run --example plot_basis || echo "Example needs fortfem module implementation"